build-job:
 stage: build
 script:
   - echo "Hello, $GITLAB_USER_LOGIN!"
deploying:
 stage: deploy
 script:
   - echo "Deployed"
   - git clone -b dev https://github.com/sherandrej/internship-repo.git
   - cd "internship-repo/Docker"
   - ls
   - docker-compose up -f "internship-repo/Docker/docker-compose.yml" -d
#   - docker-compose up -d
