build-job:
 stage: build
 script:
   - echo "Hello, $GITLAB_USER_LOGIN!"
deploying:
 stage: deploy
 script:
  # - cd "internship-repo"
  # - git checkouut dev
  # - sudo git pull origin
   - pwd
   - ls
   - sudo docker-compose -f "internship-repo/Docker/docker-compose.yml" up -d
   - echo "Deployed"
#   - docker-compose up -d
