version: "3.3"
    
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    env_file:
      - ./env/db.env
    networks:
      - wpsite
  
  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - 90:80
    volumes:
      - ./src:/var/www/html
      - ./hosts/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    networks:
      - wpsite

  php:
    image: php:7.2-fpm
    container_name: php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['~/Docker-vol/wordpress_data:/var/www/html']
  #  volumes: ['./wordpress_data:/var/www/html']
    env_file:
      - ./env/wp.env
    networks:
      - wpsite

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - apache
      - php
    networks:
      - wpsite
    links: 
      - apache

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - wpsite
    depends_on:
      - php

networks:
  wpsite:
volumes:
  src: {}
  hosts: {}
  mysql: {}
  apache: {}
  wordpress_data: {}

 
